# Generated by Django 4.0.2 on 2022-03-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url_repo',
            field=models.URLField(blank=True, default='http://exaple.com', null=True, verbose_name='ссылка'),
        ),
    ]
