# Generated by Django 4.0.2 on 2022-03-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_project_url_repo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url_repo',
            field=models.URLField(default='http://exaple.com', verbose_name='ссылка'),
        ),
    ]
